### ISSUE TITLE
Mediajel tracker upgrades

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#555]
# Description

The mediajel-tracker is close to being 4 years old. It works fine as it is but due to time and new requirements the codebase is in need of updates. We want to simplify further, the development experience of building adapters on the mediajel-tracker, ensuring a streamlined development experience that abstracts away the complexity and makes building adapters truly "simple" and maintainable.

- [x] Fix Google Ads plugin instability with some carts
- [x] Simply code on maintaing v1 and v2 trackers by reducing code duplication and usage of interfaces
- [ ] Fix tracking issues associated with v1 and v2 trackers on a single page
- [x] Add self-documenting tags feature
- [x] Cleaner way of including/excluding partner integrations dynamically
- [x] Code cleanup of partners (TTD & Mantis)
- [x] General upgrade of dependencies, mediajel-tracker now compatible with node lts (v20)
- [x] export custom `trackTrans` function so can be reused by frictionless adapters.
- [ ] Next steps for Jon & Sean on mediajel-tracker for code improvements
- [x] Codebase reduce bundle size, smaller === faster
    - [x] 7,078 lines of code, 164 files, and 290 kb bundled to;
    - [x] 3,521 lines of code, 69 files, and 40 kb bundled

# Test Plan

Test plan is to be done by Pach & Sean. NOTE: this pertains to the staging branch

- [x] Test transactions tracking of the mediajel-tracker with a supported adapter
    - [x] Test the  mediajel-tracker (v1) on a client with the legacy configuration (I.E. `version=1`).
    - [x] Test the mediajel-tracker on a client with the updated configuration (I.E. `version=2`).
- [x] Test the plugins of the mediajel-tracker with a client that uses a supported adapter
    - [x] Enabling the Google Ads plugin must send transactions to both Google Ads and our Snowplow collector
    - [x] Enabling the Bing Ads plugin must send transactions to both Bing Ads and our Snowplow collector
    - [x] Enabling both Bing Ads & Google Ads must send transactions to Bing Ads, Google Ads, and our Snowplow collector
- [x] Test Segments extension in the mediajel-tracker
    - [x] Providing an s2.pv and s2.tr parameter in the mediajel-tracker must send a pageview signal to nexxen on page load and a transaction signal to nexxen
    - [x] Provide an s3.pv and s3.tr parameters in the mediajel-tracker must send a pageview signal to dstillery on page load and a transaction signal to dstillery
- [ ] ~~2 tags on the same page with different versions must track transactions without issues~~
- [x] 2 tags on the same page with the same versions must track transactions without issues
- [ ] 2 tags on the same page with different domains must track transactions without issues 
- [x] Frictionless tags must be able to use the exported `trackTrans` function exported to the window from mediajel-tracker being rendered
