### ISSUE TITLE
Mediajel tracker enhancements

### ISSUE THREAD

**Issue by pacholoamit** [MediaJel/mediajel-tracker#567]
# Description

Due to the overhaul of the mediajel-tracker, we want to do the following:

- [ ] Replace window.tracker transaction references to window.trackTrans from the mediajel-frictionless-custom-tag.
- [ ] Implement overrides addToCart, and removeFromCart.
- [ ] Create a plan to make dynamic variable assignment. Dynamically add or update params in the tracker (Domain specific).

**Comment by pacholoamit** [comment]
Update: @SeanRizarre , create migration plan for window.trackTrans

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/219 - FOR QA

- cincinnati-menu.thelandingdispensaries.com.ts
- https://cincinnati-menu.thelandingdispensaries.com/stores/cincinnati-ohio

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/220 - FOR QA

- monroe-menu.thelandingdispensaries.com.ts
- https://monroe-menu.thelandingdispensaries.com/stores/monroe-ohio

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/221 - FOR QA

- cleveland-menu.thelandingdispensaries.com.ts
- https://cleveland-menu.thelandingdispensaries.com/stores/cleveland-ohio/

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/222 - FOR QA

- columbus-menu.thelandingdispensaries.com.ts
- https://columbus-menu.thelandingdispensaries.com/stores/columbus-ohio

**Comment by SeanRizarre** [comment]
Updates:
-Code Reviewed Jon's PRs and merged. 
-Next steps: Do test transactions to test out that it's working before marking done on the list.

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/265 - FOR QA

- [www.thegreendragoncbd.com.ts](http://www.thegreendragoncbd.com.ts/)
- https://www.thegreendragoncbd.com/

**Comment by ZeeLiger** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/266
- direct.hyperwolf.com.ts


https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/267/files
- huronmenu.myfisci.com.ts


https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/268
- lowkeydispensary.com.ts


( Only commented out code )
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/269
- seaweedmaine.com.ts (comment the code since it's using dutchie-iframe, make a test transaction afterwards)


https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/270
- [www.psychedelicszone.com.ts](http://www.psychedelicszone.com.ts/)


https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/271
- [www.thelandingdispensaries.com.ts](http://www.thelandingdispensaries.com.ts/)

**Comment by ZeeLiger** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/272
- menus.dispenseapp.com.ts



https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/273
- [www.diamondcbd.com.ts](http://www.diamondcbd.com.ts/)

**Comment by jonmediajel** [comment]
Try to see if Budmary works with dutchie-iframe without the use of a custom tag

https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/274

**Comment by jonmediajel** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/265
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/274

Needed someone who can review for me on this, please, in order for us to merge this in. Thanks

**Comment by ZeeLiger** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/271
- [www.thelandingdispensaries.com.ts](http://www.thelandingdispensaries.com.ts/)

Before Merge: 

![Image](https://github.com/user-attachments/assets/869de488-0dd3-4af3-a4b9-6869b2bc22ce)

![Image](https://github.com/user-attachments/assets/93697ec2-cee9-4c47-beee-26041c26a166)

![Image](https://github.com/user-attachments/assets/11880928-186b-47e9-a468-5b849e899c7d)

![Image](https://github.com/user-attachments/assets/72094932-34b5-4dd4-9e7e-114833e4c551)

![Image](https://github.com/user-attachments/assets/fef00613-dac3-47f3-9219-cbe8aa970369)

**Comment by Russell0813** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/271

[www.thelandingdispensaries.com.ts](http://www.thelandingdispensaries.com.ts/)
AFTER MERGE (ALL WORKS)
![Image](https://github.com/user-attachments/assets/3b65689e-46cd-470d-af54-70e66253d8a1)

![Image](https://github.com/user-attachments/assets/0c885669-c426-497b-9d97-4ebc5c7836c6)

![Image](https://github.com/user-attachments/assets/88d47243-57f4-4c43-ad5f-a4872c474509)

![Image](https://github.com/user-attachments/assets/5ca96168-75ca-454f-8ba8-4d892697a3ff)

**Comment by Russell0813** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/268

lowkeydispensary.com.ts
AFTER MERGE (WORKS)
![Image](https://github.com/user-attachments/assets/deec83aa-b216-4e7b-8cc7-eb64ce1ea0d3)

**Comment by Russell0813** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/267/files

huronmenu.myfisci.com.ts
AFTER MERGE (WORKS)
![Image](https://github.com/user-attachments/assets/de3167e9-9943-4609-a516-879c65d9d3b5)

**Comment by jonmediajel** [comment]
![Image](https://github.com/user-attachments/assets/91e002b9-5413-4a48-9bc0-b052122d433a)

The green dragon cbd after enhancements

**Comment by Russell0813** [comment]
https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/267/files

huronmenu.myfisci.com.ts

WORKS AFTER MERGE
![Image](https://github.com/user-attachments/assets/f3026461-9979-41de-8d9b-0240576cbb76)

https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/268

lowkeydispensary.com.ts
WORKS AFTER MERGE
![Image](https://github.com/user-attachments/assets/c2698780-8167-436a-8624-bbfafc692885)

**Comment by ZeeLiger** [comment]
psychadeliczone does not work even with the woocomerce cart after checking that their site is woocomerce 

![Image](https://github.com/user-attachments/assets/24d440be-81d6-4901-a432-3ed2d8a0382e)

![Image](https://github.com/user-attachments/assets/082e208e-be72-4598-8e8d-33ae38a9ca4f)

**Comment by ZeeLiger** [comment]
There are also no current campaigns running with psychedelic zone

**Comment by jonmediajel** [comment]
budmary after merging. 

![Image](https://github.com/user-attachments/assets/22c2ea6f-42a4-494c-bcd3-87f86b326da4)

**Comment by Russell0813** [comment]
BEFORE:

[www.diamondcbd.com.ts] (for PR and QA)
![Image](https://github.com/user-attachments/assets/d440dac3-c0c5-464e-acc1-abb1277a045f)

[www.hrdelivery.co.ts](http://www.hrdelivery.co.ts/) (unable to test transaction.)
![Image](https://github.com/user-attachments/assets/00b0cf94-e829-4ad3-8290-d38ba4aa8982)

[www.offer.heycruisechews.com.ts]  Website inaccessible
![Image](https://github.com/user-attachments/assets/316a78c3-a363-47cc-9733-d7b95e65d013)

[www.ticketmaster.com.ts] Tag not installed on their website.

**Comment by Russell0813** [comment]
PR for diamondcbd and hrdelivery: https://github.com/MediaJel/mediajel-frictionless-custom-tag/pull/334

**Comment by Russell0813** [comment]
Not yet having test transaction. no cash left 🥲
